@startuml Licium Context
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml


Person(holder , "Rights Holder")

System_Boundary(licium, "Licium"){
    Container(frontend, "Frontend", "HTML5", "GUI")
    Container(backend, "Backend", "Micronaut - Java Runtime Image / GraalVM Image")
}


System_Ext(ams, "Assent Management System", "Contains copyrightable media files. Can be as simple as the local filesystem, or as complex as external software products")
System_Ext(blockchain, "Blockchain Network", "Stores ISCC on public ledger")

Rel(holder, frontend, "Access with web browser")
Rel(frontend, backend, "configure, read state, trigger actions", "HTTP-JSON")
Rel(backend, blockchain, "sync & create transactions", "web3 JSON-RPC")
Rel(backend, ams, "read", "filesystem driver")


@enduml
