version: "3.7"
services:
  iscc-service:
    build: iscc-service/.
    labels:
      - traefik.http.routers.iscc-service.rule=PathPrefix(`/api`)
      - traefik.http.services.iscc-service.loadbalancer.server.port=8080
  licium-webapp:
    build: licium-webapp/.
    labels:
      - traefik.http.routers.licium-webapp.rule=PathPrefix(`/`)
  reverse-proxy:
    image: traefik:v2.2
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock