name: Docker login test

on:
  push:
  pull_request:

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
    -  name: Login to DockerHub
       uses: docker/login-action@v1.8.0 
       with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
   
