name: Ethereum

on:
  push:
  pull_request:

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        
    - run: npm install -g truffle truffle-assertions ganache-cli
    - run: |
        ganache-cli & 
        truffle test
      working-directory: ethereum
